name: install-test-build-deploy

on: [push]

env:
    CI: true

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            # BEGIN INSTALL
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - uses: actions/cache@v1
              id: cache-node_modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install --frozen-lockfile
              if: steps.cache-node_modules.outputs.cache-hit != 'true'
            # END INSTALL

    test:
        runs-on: ubuntu-latest
        needs: [install]

        steps:
            # BEGIN INSTALL
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - uses: actions/cache@v1
              id: cache-node_modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install --frozen-lockfile
              if: steps.cache-node_modules.outputs.cache-hit != 'true'
            # END INSTALL

            - run: yarn build:ts
            - run: yarn test

    build:
        if: github.ref != 'refs/heads/master' # see `build-and-deploy`
        runs-on: ubuntu-latest
        needs: [install]

        steps:
            # BEGIN INSTALL
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - uses: actions/cache@v1
              id: cache-node_modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install --frozen-lockfile
              if: steps.cache-node_modules.outputs.cache-hit != 'true'
            # END INSTALL

            - run: yarn build:prod

    build-and-deploy:
        if: github.ref == 'refs/heads/master' # see `build`

        runs-on: ubuntu-latest
        needs: [install, test]

        steps:
            # BEGIN BUILD

            # BEGIN INSTALL
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - uses: actions/cache@v1
              id: cache-node_modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install --frozen-lockfile
              if: steps.cache-node_modules.outputs.cache-hit != 'true'
            # END INSTALL

            - run: yarn build:prod
            # END BUILD

            - run: yarn docker:deploy
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

            - run: git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
            - run: git config --global user.name ${{ secrets.GIT_USER_NAME }}

            # create new version (& push to github) (skips ci to avoid an infinite loop)
            - run: yarn lerna version

            # get the latest tag
            # see https://github.com/actions/starter-workflows/issues/68#issuecomment-552074596
            - run: echo "::set-env name=LATEST_TAG::$(git describe --tags --abbrev=0)"

            # print for debugging
            - run: echo "$LATEST_TAG"

            - run: yarn docker:tag-version
            #   env:
            #       LATEST_TAG: ${{ LATEST_TAG }}

            - run: yarn docker:push-tagged-version
            #   env:
            #       LATEST_TAG: ${{ LATEST_TAG }}
