#
# We're using artifacts to persist data between jobs - see
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow
#

name: install-test-build

on: [push]

env:
    CI: true

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - uses: actions/cache@v1
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - run: yarn install --frozen-lockfile

            - uses: actions/upload-artifact@v1
              with:
                  name: node_modules
                  path: node_modules

    test:
        runs-on: ubuntu-latest
        needs: [install]

        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: node_modules
                  path: node_modules

            - run: yarn build:ts
            - run: yarn test

    build:
        runs-on: ubuntu-latest
        needs: [install, test]

        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: node_modules
                  path: node_modules

            - run: yarn build:prod

            - uses: actions/upload-artifact@v1
              with:
                  name: build
                  path: .

    deploy:
        if: github.ref == 'master' # only on master branch

        runs-on: ubuntu-latest
        needs: [install, test, build]

        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: build
                  path: .

            - run: yarn docker:deploy
            # create new version (& push to github) (skips ci to avoid an infinite loop)
            - run: yarn lerna version

            # get the latest tag
            - run: echo "export LATEST_TAG=$(git describe --tags --abbrev=0)" >> $BASH_ENV

            # print for debugging
            - run: echo "$LATEST_TAG"

            - run: yarn docker:tag-version

            - run: yarn docker:push-tagged-version
